environment: production
chdir: /home/sinatra_template_app/webapp/current
address: 127.0.0.1
user: sinatra_template_app_user
group: sinatra_template_app_group
port: 5000
pid: /home/sinatra_template_app/webapp/current/tmp/pids/thin.pid
rackup: /home/sinatra_template_app/webapp/current/config.ru
log: /home/sinatra_template_app/webapp/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 128
daemonize: true

